/** 
* Copyright 2016 Marianna D'Errico, Simone Bna'
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*    http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License. 
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define MAX_STRING 500
#define MAX_WORDS 2000

int ArgPos(char *str, int argc, char **argv) {
  int a;
  for (a = 1; a < argc; a++) if (!strcmp(str, argv[a])) {
    if (a == argc - 1) {
      printf("Argument missing for %s\n", str);
      exit(1);
    }
    return a;
  }
  return -1;
}

int main(int argc, char **argv) {
  
  char input_file[MAX_STRING], input_words_file[MAX_STRING], omatrix_file[MAX_STRING],\
    olabel_file[MAX_STRING], oclass_file[MAX_STRING], buf[MAX_STRING], str1[MAX_STRING], word_list[MAX_WORDS][MAX_STRING], class_list[MAX_WORDS][MAX_STRING];
  int i, j, k, skip, nrow, mcol, nwords, nwords_found, word_exist[MAX_WORDS];
  float number;
  
  if (argc == 1) {
    printf("Word2Vec to cluto matrix converter\n\n");
    printf("Options:\n");
    printf("Parameters:\n");
    printf("\t-input_vector <file>\n");
    printf("\t\tOutput vector file generated by word2vec\n");
    printf("\t-input_word_list <file>\n");
    printf("\t\tList of words to be found in the word vector generated by word2vec\n");
    printf("\t-output_matrix <file>\n");
    printf("\t-output_label <file>\n");
    printf("\nExamples:\n");
    printf("./word2vectocluto -input_vector vectors.txt -input_word_list word_list.txt -output_matrix vectors.mat -output_label vectors_label.mat\n\n");
    return 0;
  }
  
  if ((i = ArgPos((char *)"-input_vector", argc, argv)) > 0) strcpy(input_file, argv[i + 1]);
  if ((i = ArgPos((char *)"-input_word_list", argc, argv)) > 0) strcpy(input_words_file, argv[i + 1]);
  if ((i = ArgPos((char *)"-output_matrix", argc, argv)) > 0) strcpy(omatrix_file, argv[i + 1]);
  if ((i = ArgPos((char *)"-output_label", argc, argv)) > 0) strcpy(olabel_file, argv[i + 1]);
  if ((i = ArgPos((char *)"-output_class_label", argc, argv)) > 0) strcpy(oclass_file, argv[i + 1]);

  FILE *fi;
  fi = fopen(input_file, "r");
  
  if( fi == NULL )
  {
    printf("A.\n");
    printf("Error while opening the %s file.\n", input_file);
    exit(EXIT_FAILURE);
  }
  
  FILE *fi_words;
  fi_words = fopen(input_words_file, "r");
  
  if( fi_words == NULL )
  {
    printf("B.\n");
    printf("Error while opening the %s file.\n", input_words_file);
    exit(EXIT_FAILURE);
  }
  
  FILE *fo_matrix;
  fo_matrix = fopen(omatrix_file, "w");
  
  if( fo_matrix == NULL )
  {
    printf("C.\n");
    printf("Error while opening the %s file.\n", omatrix_file);
    exit(EXIT_FAILURE);
  }
   
  FILE *fo_label;
  fo_label = fopen(olabel_file, "w");
  
  if( fo_label == NULL )
  {
    printf("D.\n");
    printf("Error while opening the %s file.\n", olabel_file);
    exit(EXIT_FAILURE);
  }
  
  FILE *fo_class;
  fo_class = fopen(oclass_file, "w");
  
  if( fo_class == NULL )
  {
    printf("D.\n");
    printf("Error while opening the %s file.\n", oclass_file);
    exit(EXIT_FAILURE);
  }
  
  /* init word_exist to false */
  for (i=0; i<MAX_WORDS; i++) {
    word_exist[i] = 0; 
  }
  
  /* read the word list */
  i = 0;
  while (fscanf(fi_words, "%s", buf) != EOF) {
    if(i%2 == 0) {
      strcpy(word_list[i/2], buf);
    }
    else {
      strcpy(class_list[i/2], buf);
    }
    /*printf("I read %s from file %s\n", word_list[i], input_words_file);*/
    if(i%2 == 0) {
    for (j=0; j<(i/2); ++j) {
      if (!strcmp(word_list[i/2], word_list[j])) {
        printf("duplicate word : < %s >\n", word_list[j]);
	fscanf(fi_words, "%s", buf);
        --i;
      }
    }
    }
    ++i;
  }
  nwords = i/2;
  nwords_found = 0;
  printf("I read %d words\n", nwords);
  
  printf("Reading from file %s ...\n", input_file);
  
  fscanf(fi, "%d", &nrow);
  fscanf(fi, "%d", &mcol);
  
  fprintf(fo_matrix, "%-8d %-8d\n", nwords, mcol);
  
  i = 0;
  j = 0;
  k = 0;
  skip = 1;
  for (i = 0; i < nrow; i++) {
    skip = 1;
    
    fscanf(fi, "%s", str1);
    
    /** find the word in the list*/
    for (k = 0; k < nwords; k++) {
      if (!strcmp(str1, word_list[k])) {
        /*printf("I found the word %s in the word list\n", str1);*/
	word_exist[k] = 1;
        skip = 0;
	fprintf(fo_class, "%s\n", class_list[k]);
      }
    }
    
    if(!skip) {
      fprintf(fo_label, "%s\n", str1);
    }
     
    for (j = 0; j < mcol; j++) {
      fscanf(fi, "%f", &number);
      if(!skip) {
        fprintf(fo_matrix, "%f ", number);
      }
    }
    if(!skip) {
      fprintf(fo_matrix, "\n");
    }
  }
  
  for(i=0; i<nwords; i++) {
    if(word_exist[i] == 0) {
      printf("The word < %s > from the list does not exist in the corpus.\n", word_list[i]);
    }
    else {
      nwords_found ++;
    }
  }
  
  printf("%d %d\n", nwords_found, mcol);
  rewind(fo_matrix);
  fprintf(fo_matrix, "%-8d %-8d\n", nwords_found, mcol);
  
  printf("...Done.\n");
  
  fclose(fi_words);
  fclose(fo_matrix);
  fclose(fo_label);
  fclose(fo_class);
  fclose(fi);
  
  return 0;
}